version: "3.4"
services:
  api:
    image: ghcr.io/lnformbu-insight/fabrikam-api:latest
    ports:
      - "3001:3001"   
    environment:
        MONGODB_CONNECTION: mongodb://mongo:27017/contentdb  
  web:
    image: ghcr.io/lnformbu-insight/fabrikam-web:latest
    depends_on:
        - api
    environment:
        CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"